// Generalized schema for any Stanford undergraduate major program sheet.
// One MajorConfig per major (generated by LLM from PDF upload, or hand-encoded).

export interface CourseOption {
  dept: string;    // e.g. "CS", "MATH", "STATS"
  number: string;  // e.g. "107E", "224N", "315A"
  name?: string;   // optional display name
  units?: number;
}

export type SlotType =
  | 'required'       // exactly this one course
  | 'pick-one'       // one of 2–5 equivalent alternatives
  | 'pick-from-list' // student fills `count` slots from the options list
  | 'any-approved'   // external/unenumerated course list: tracked by user manually
  | 'manual';        // non-course milestone (portfolio, declaration, review, etc.)

export interface Slot {
  id: string;
  label: string;
  type: SlotType;
  options: CourseOption[];
  count?: number;               // pick-from-list: how many courses to fill (default 1)
  times?: number;               // required/pick-one: how many separate enrollments needed (e.g. seminar taken 3 quarters)
  minUnits?: number;            // slot needs at least this many units (e.g. senior project ≥ 3)
  minLevel?: 100 | 200 | 300;  // course number must be at this level or higher (e.g. 200 = 200+)
  maxCountedUnits?: number;    // at most this many units from this slot count toward totalMinUnits
  optional?: boolean;
  note?: string;                // shown as tooltip / footnote
  listUrl?: string;             // link to the official approved-course list (TiS, WIM, etc.)
  mutuallyExclusive?: string[]; // other slot IDs in the same section that compete with this one;
                                // only the first satisfied slot in the group counts
}

/** One option within a pick-one-group section (e.g. capstone Option A / B / C). */
export interface SectionOption {
  id: string;
  name: string;
  note?: string;
  slots: Slot[];
}

export interface SectionSelectorOption {
  id: string;
  name: string;
  minUnits?: number;
  note?: string;
  sections?: MajorSection[];
}

export interface MajorSection {
  id: string;
  name: string;
  minUnits?: number;           // actual unit total from filled courses must reach this (checked beyond slot count)
  unitOnly?: boolean;          // progress is defined only by minUnits; do not display/count a course minimum
  minCourses?: number;
  maxCountedUnits?: number;    // at most this many units from this section count toward totalMinUnits (e.g. "up to 10 non-ECON units")
  maxOverlapUnits?: number;    // max units from this section that can overlap with another program
  allowDoubleCount?: boolean;  // courses in this section can also count for another program (e.g. shared foundations)
  doubleCountGroup?: string;   // courses may overlap with sections in OTHER groups but not the same group (e.g. Art History temporal vs. geographic distribution)
  excludeFromProgramUnits?: boolean; // required coursework completed in addition to the program's stated unit minimum
  phase?: 'pre-major' | 'major'; // 'pre-major' = prerequisites to declare; shown collapsed by default
  trackSelector?: boolean;     // when true, section renders a track/concentration picker instead of slots
  selectorLabel?: string;      // optional persisted selector shown within an ordinary section
  selectorOptions?: SectionSelectorOption[];
  note?: string;               // shown at the top of the section (for trackSelector sections especially)
  slots: Slot[];
  /** Student completes N of these option groups; section done when N groups are complete. */
  pickOneGroup?: SectionOption[];
  /** How many groups in pickOneGroup must be completed. Defaults to 1. */
  pickGroupCount?: number;
}

export type ProgramCategory = 'major' | 'minor' | 'coterm';

/**
 * A concentration/track within a program (e.g. MS&E tracks, CS specializations).
 * When `tracks` is present on a MajorConfig, a track selector is shown and only
 * the selected track's sections are rendered.
 */
export interface Track {
  id: string;
  name: string;
  minUnits?: number;
  sections: MajorSection[];
}

/** A program-wide requirement satisfied by any course anywhere in the program (e.g. CS coterm "Significant Implementation Experience"). Can fully double-count with any section. */
export interface MetaRequirement {
  id: string;
  label: string;
  note?: string;
  listUrl?: string;
  options: CourseOption[];  // courses that qualify; empty = any-approved (listUrl must be set)
  minCount: number;         // how many must appear somewhere in the program (usually 1)
}

export interface MajorConfig {
  id: string;
  name: string;
  school: string;
  year: string;
  category?: ProgramCategory; // default 'major'
  totalMinUnits?: number;     // minimum total units across ALL sections (e.g. 26 for CS minor)
  bulletinUrl?: string;       // canonical bulletin.stanford.edu/programs/{ID}/ URL for this program
  sections: MajorSection[];
  tracks?: Track[];           // optional concentration/track selector
  metaRequirements?: MetaRequirement[]; // program-wide cross-section requirements
  /** Explicit exceptions that may satisfy matching slots in more than one section of this program. */
  doubleCountCourses?: CourseOption[];
  /** Courses that explicitly satisfy the WIM requirement for this program (from program sheet). */
  wimCourses?: CourseOption[];
  /** Number of WIM courses required. Defaults to 1; use for programs whose WIM is a sequence. */
  wimMinCount?: number;
  /** Set false when WIM is shown only in the universal COLLEGE & Writing section. */
  showWimInProgram?: boolean;
}
